load_model: True
print_device: False
run_optimizer: True
#if tensorboard_frequency is 0, tensorboard is not used
#tensorboard_frequency: 0
tensorboard_frequency: 1000
validation_batch_frequency: 1000
#validation_batch_frequency: 10
positive_is_positive: True