model:
  number_of_epochs: 5000
  batch_size: 10
  translation_hidden_size: 3000
  encoder_hidden_states: [1500, 1000, 500]
  decoder_hidden_states: [1000, 1500]
  learn_rate: 0.01
  dropout: 0.1
  bidirectional_encoder: False
  curriculum_training: True

embedding:
  min_word_occurrences: 0
  word_size: 100
  should_train: False

loss:
  upper_range: 5.0
  lower_range: 3.0

sentence:
  #limit: 300000
  limit: 1000
  min_length: 3
  max_length: 15
