model:
  number_of_epochs: 5000
  batch_size: 5
  translation_hidden_size: 150
  encoder_hidden_states: [45, 30]
  decoder_hidden_states: [45]
  learn_rate: 0.1
  dropout: 0.1
  bidirectional_encoder: False
  curriculum_training: False

embedding:
  min_word_occurrences: 0
  word_size: 10
  should_train: False

loss:
  upper_range: 5.0
  lower_range: 3.0

sentence:
  #limit: 300000
  limit: 5
  min_length: 3
  max_length: 15
