glove_file: data/glove.6B/glove.6B.50d.txt
limit_sentences:
batch_size: 10
translation_hidden_size: 10
train_embeddings: False
encoder_hidden_states: [100, 50]
decoder_hidden_states: [50, 100]
discriminator_hidden_states: [10, 10]
learn_rate: 0.01
sentence_length: 5
debug: False