model:
  number_of_epochs: 5000
  batch_size: 10
  encoder_hidden_states: [1500, 1000, 500]
  decoder_hidden_states: [1000, 1500]
  learn_rate: 1.1
  dropout: 0.1
  bidirectional_encoder: False
  curriculum_training: True
#  margin_coefficient: 1.
  margin: 1.0
  random_words_size: 5

embedding:
  min_word_occurrences: 2
  word_size: 100
  should_train: False

loss:
  upper_range: 3.0
  lower_range: 1.5

sentence:
  limit: 1000
#  limit: 5
  min_length: 3
  max_length: 15
