model:
  number_of_epochs: 5000
  batch_size: 5
  translation_hidden_size: 250
  encoder_hidden_states: [1000, 500, 100]
  decoder_hidden_states: [500, 1000]
  learn_rate: 0.01
  dropout: 0.0
  bidirectional_encoder: False
  curriculum_training: False

embedding:
  min_word_occurrences: 0
  word_size: 10
  should_train: True

loss:
  upper_range: 5.0
  lower_range: 3.0

sentence:
  #limit: 300000
  limit: 5
  min_length: 3
  max_length: 15